// ⚠️ NOTE: This file is NOT used in Prisma 7
// Prisma 7 no longer uses prisma.config.ts
// All configuration should be in prisma/schema.prisma
// You can safely delete this file

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
